# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build tukon"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["tukon_left", "tukon_right"]'
      branches: '["petejohanson/zmk/power/domains-and-device-runtime"]'
      alphas: '[qwerty]'
      layers: '[flip]'
      kconfig: '["#define CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y"]'
